data(iris)
dim(iris)
str(iris)
summary(iris)
apply(iris[, 1:4], 2, sd)
aggregate(. ~ Species, data = iris, FUN = function(x) c(mean = mean(x), sd = sd(x)))
quantile(iris$Sepal.Width)
quantile(iris$Sepal.Length)
iris1 <- iris
iris1$Sepal.Length.Cate <- cut(iris1$Sepal.Length, breaks = quantile(iris1$Sepal.Length))
head(iris1)
aggregate(. ~ Species + Sepal.Length.Cate, data = iris1, FUN = mean)
aggregate(. ~ Species + Sepal.Length.Cate, data = iris1, FUN = function(x) mean(x, na.rm = TRUE))
pivot_table <- aggregate(. ~ Species + Sepal.Length.Cate, data = iris1, FUN = length)
print(pivot_table)